### ISSUE TITLE
2 apks

### ISSUE THREAD

**Issue by jcl2023** [lilstiffy/MockGps#3]
What are differences between these 2 APKs in app/release:

app-release.apk and mockgps-app-release.apk

My own debug build behaves like app-release.apk which shows no map for me to choose a location.

Thanks,

**Comment by lilstiffy** [comment]
1.0.3(4) Only has one .apk and that's the current release

If you want to run a debug build, built from your own android studio you need to use your own maps api key. 
I have restricted my api-key to the keystore i signed the release app with. 
mockgps-app-release.apk is signed and should have a map working.

If you need help setting everything up you could add me on discord :)

**Comment by lilstiffy** [comment]
https://github.com/lilstiffy/MockGps/releases/tag/1.0.3(4)
